// Generated by CoffeeScript 1.7.1
(function() {
  var iOS;

  iOS = navigator.userAgent.match(/(iPad|iPhone|iPod)/g);

  if (iOS && $(".container").css("min-height") === "100vh") {
    $(".container").css("min-height", "100px");
  }

  $("body").css("min-height", "100px");

  if (iOS && $(".container").css("min-width") === "100vh") {
    $(".container").css("min-width", "100px");
  }

  jQuery(function() {
    var about, blog, colophon, contact, home, move, travel;
    $(".slide-nav").on("click", function() {
      if ($('.icon-menu').is(":visible")) {
        $('.icon-close').show();
        $('.horizontal').show();
        $("#sidebar").css({
          'background-color': '#F1F1F1'
        });
        $('.vertical').hide();
        $('.icon-menu').hide();
        $('.container').css({
          'margin-left': '200px'
        });
      } else if (($(window).width() < 720) && $('.icon-menu').is(":visible")) {
        $('.horizontal').show();
        $('.vertical').hide();
        $('.icon-menu').hide();
        $('.icon-close').show();
      } else {
        $('.icon-menu').show();
        $('.icon-close').hide();
        $('.horizontal').hide();
        $('.vertical').show();
        $("#sidebar").css({
          'background-color': '#FFFFFF'
        });
        $('.container').css({
          'margin-left': '100px'
        });
      }
      return $(".nav-links").animate({
        width: 'toggle'
      }, 600);
    });
    $(".show-sub-links").on("click", function() {
      return $(".sub-links").animate({
        width: 'toggle'
      }, 600);
    });
    home = $('[data-section="home"]');
    travel = $('[data-section="travel"]');
    about = $('[data-section="about"]');
    blog = $('[data-section="blog"]');
    contact = $('[data-section="contact"]');
    colophon = $('[data-section="colophon"]');
    $('[data-show="home"]').on("click", function() {
      $('[data-section="home"]').show();
      travel.hide();
      about.hide();
      blog.hide();
      contact.hide();
      return colophon.hide();
    });
    $('[data-show="travel"]').on("click", function() {
      $('[data-section="travel"]').show();
      home.hide();
      about.hide();
      blog.hide();
      contact.hide();
      return colophon.hide();
    });
    $('[data-show="about"]').on("click", function() {
      $('[data-section="about"]').show();
      home.hide();
      travel.hide();
      blog.hide();
      contact.hide();
      return colophon.hide();
    });
    $('[data-show="blog"]').on("click", function() {
      $('[data-section="blog"]').show();
      home.hide();
      travel.hide();
      contact.hide();
      about.hide();
      return colophon.hide();
    });
    $('[data-show="contact"]').on("click", function() {
      $('[data-section="contact"]').show();
      home.hide();
      travel.hide();
      blog.hide();
      about.hide();
      return colophon.hide();
    });
    $('[data-show="colophon"]').on("click", function() {
      $('[data-section="colophon"]').show();
      home.hide();
      travel.hide();
      about.hide();
      contact.hide();
      return blog.hide();
    });
    setTimeout((function() {
      $('[data-home="img-slide"]').removeClass("pic-1", 500);
      return $('[data-home="img-slide"]').addClass("pic-2", 500);
    }), 10000);
    setTimeout((function() {
      $('[data-home="img-slide"]').removeClass("pic-2", 500);
      return $('[data-home="img-slide"]').addClass("pic-3", 500);
    }), 20000);
    setTimeout((function() {
      $('[data-home="img-slide"]').removeClass("pic-3", 500);
      return $('[data-home="img-slide"]').addClass("pic-4", 500);
    }), 30000);
    setTimeout((function() {
      $('[data-home="img-slide"]').removeClass("pic-4", 500);
      return $('[data-home="img-slide"]').addClass("pic-1", 500);
    }), 40000);
    move = $('[data-text="position"]').outerWidth() / 2;
    $('[data-text="position"]').css({
      'margin-left': -move
    });
    return $(window).on('resize', function() {
      move = $('[data-text="position"]').outerWidth() / 2;
      return $('[data-text="position"]').css({
        'margin-left': -move
      });
    });
  });

}).call(this);
